import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
})

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next.js and is not ours to lint.
    ignores: ['.next/**', 'node_modules/**', 'public/**', 'scripts/**', 'next-env.d.ts'],
  },
  {
    rules: {
      // Long-form article HTML is compiled from our own MDX through
      // remark/rehype with no raw-HTML pass-through, so there is no
      // untrusted input reaching dangerouslySetInnerHTML.
      'react/no-danger': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
]

export default config
