import { execSync } from 'node:child_process'

/*
 * Which commit this build came from.
 *
 * Deploys here are pull-based: cron on the server notices origin/main has moved
 * and builds it. Nothing reports back, so "did my push actually go live?" was
 * answerable only by looking for a change on the page and guessing — and a cron
 * that silently stopped fetching looks exactly like a deploy that has not
 * finished yet. Baking the commit into the build lets /api/version answer it,
 * and lets CI wait for a specific commit rather than a plausible-looking page.
 *
 * Read at build time from the checkout being built, which is the server's own
 * checkout during a deploy. Git being absent is not an error — it just means
 * the build cannot identify itself, and the endpoint says so.
 */
function resolveBuildSha() {
  const provided = process.env.BUILD_SHA || process.env.GITHUB_SHA
  if (provided) return provided.trim()

  try {
    return execSync('git rev-parse HEAD', {
      stdio: ['ignore', 'pipe', 'ignore'],
      encoding: 'utf8',
    }).trim()
  } catch {
    return ''
  }
}

/*
 * Canonical host. Every URL the site emits — canonical tags, sitemap entries,
 * JSON-LD @ids, RSS links — is built from NEXT_PUBLIC_SITE_URL through
 * `absoluteUrl()`, so the www/non-www redirect below derives its target from
 * that same value and cannot drift out of agreement with them.
 */
const canonicalOrigin = new URL(
  (process.env.NEXT_PUBLIC_SITE_URL || 'https://globifytech.com').replace(/\/$/, ''),
).origin
const canonicalHost = new URL(canonicalOrigin).host

/** The twin of the canonical host: www.x when x is canonical, and vice versa. */
const duplicateHost = canonicalHost.startsWith('www.')
  ? canonicalHost.slice(4)
  : `www.${canonicalHost}`

/*
 * Where the build is written.
 *
 * Normally `.next`, which is also what `next start` serves. During a deploy it
 * is pointed somewhere else so the build never touches the directory being
 * served — see scripts/deploy.sh. Building in place rewrites `.next/static`
 * while Passenger is still serving prerendered HTML that references the old
 * hashed filenames, and for the minutes that takes, every visitor gets a page
 * whose stylesheets 404: correct markup, no CSS, unreadable.
 */
const distDir = process.env.NEXT_DIST_DIR || '.next'

/** @type {import('next').NextConfig} */
const nextConfig = {
  distDir,
  reactStrictMode: true,
  poweredByHeader: false,
  compress: true,

  /* Inlined into the build, so `/api/version` reports the commit that produced
     the running bundle rather than whatever the server's checkout happens to be
     sitting on now — those differ precisely when a deploy half-failed, which is
     the case worth detecting. */
  env: {
    BUILD_SHA: resolveBuildSha(),
    BUILD_TIME: new Date().toISOString(),
  },

  // Trailing slashes off => single canonical URL shape (no duplicate-content penalty).
  trailingSlash: false,

  images: {
    // Local WebP/AVIF assets are pre-generated by scripts/generate-images.mjs.
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [360, 420, 640, 768, 1024, 1280, 1536, 1920],
    imageSizes: [64, 96, 128, 192, 256, 384],
    minimumCacheTTL: 60 * 60 * 24 * 365,
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },

  experimental: {
    // Tree-shake barrel imports from icon/animation packages -> smaller JS payload.
    optimizePackageImports: ['lucide-react'],
  },

  // 301 redirects. Add legacy URLs here as the site evolves.
  async redirects() {
    /* Retired course URLs, kept alive for inbound links and for the blog
       articles that still point at them.

       Only two survive as course-to-course redirects. The catalogue is three
       marketing programmes now, and a redirect is a claim that the destination
       is what the visitor was looking for — so anything without a genuine
       successor goes to the catalogue below instead of to the nearest-sounding
       name. */
    const retiredCourses = [
      ['digital-marketing', 'digital-media-marketing-with-ai'],
      ['digital-marketing-with-ai', 'digital-media-marketing-with-ai'],
    ].map(([from, to]) => ({
      source: `/courses/${from}`,
      destination: `/courses/${to}`,
      permanent: true,
    }))

    /* No successor close enough to name. Pointing "AI Chatbots & Business
       Automation" at Facebook Automation because both say "automation" would
       land visitors on a course about something else — worse than the
       catalogue, which at least lets them choose. */
    const retiredToCatalogue = [
      /* Withdrawn in 2026, when development, commerce and design came out of
         the catalogue. Nothing among the three surviving marketing programmes
         is a fair substitute for any of them, and `retiredCourseSlugs` in
         src/lib/courses.ts is the same list — it drives the database prune. */
      'full-stack-development-with-ai',
      'tiktok-shop',
      'graphic-designing',
      'video-editing',

      /* Older lineages whose successors have themselves now been withdrawn.
         Repointed straight here rather than left chaining through a dead
         course: two 301s to reach the same page splits the signal and costs
         the visitor a round trip. */
      'ai-and-automation',
      'web-development',
      'python-programming',
      'wordpress-development',
      'ui-ux-design',
      'canva-mastery',
      'amazon-virtual-assistant',
      'shopify-dropshipping',
      'full-stack-web-development-with-ai',
      'tiktok-shop-mastery',

      // Never had a counterpart in this repository's catalogue at all.
      'freelancing-mastery',
      'office-automation',
      'agentic-ai-and-workflow-management',
      'ai-chatbots-and-business-automation',
    ].map((from) => ({
      source: `/courses/${from}`,
      destination: '/courses',
      permanent: true,
    }))

    /* Host consolidation: send the duplicate host to the canonical one so
       Google merges the signals instead of splitting them across two hosts.
       `has` matches the Host header exactly, so localhost, *.vercel.app
       previews and the canonical host itself are all left untouched — only
       the literal duplicate redirects, which rules out a loop. */
    const canonicalHostRedirect = {
      source: '/:path*',
      has: [{ type: 'host', value: duplicateHost }],
      destination: `${canonicalOrigin}/:path*`,
      permanent: true,
    }

    return [
      canonicalHostRedirect,
      ...retiredCourses,
      ...retiredToCatalogue,
      { source: '/home', destination: '/', permanent: true },
      { source: '/courses/index', destination: '/courses', permanent: true },
      { source: '/blogs', destination: '/blog', permanent: true },
      { source: '/blogs/:slug', destination: '/blog/:slug', permanent: true },

      /* Azadi-campaign posts renamed to evergreen slugs when the sale theme
         was retired — keep the old URLs alive for inbound links. */
      {
        source: '/blog/14-august-azadi-sale-50-percent-off-professional-courses',
        destination: '/blog/50-percent-off-professional-courses-guide',
        permanent: true,
      },
      {
        source: '/blog/limited-time-50-percent-off-azadi-offer',
        destination: '/blog/course-fees-50-percent-discount',
        permanent: true,
      },
      {
        source: '/blog/celebrate-independence-by-investing-in-yourself',
        destination: '/blog/the-case-for-investing-in-yourself',
        permanent: true,
      },
      { source: '/contact-us', destination: '/contact', permanent: true },
      { source: '/about-us', destination: '/about', permanent: true },
      { source: '/privacy', destination: '/privacy-policy', permanent: true },
      { source: '/terms-and-conditions', destination: '/terms', permanent: true },
      { source: '/rss', destination: '/feed.xml', permanent: true },
    ]
  },

  /* The callback URL registered in the Meta developer app is the short, public
     `/webhook`, while the handler lives with the other route handlers under
     `/api/webhooks/meta`. A rewrite serves both from one implementation — and
     it has to be a rewrite, not a redirect: Meta does not follow 3xx on webhook
     delivery, so the registered path must answer 200 itself. */
  async rewrites() {
    return [{ source: '/webhook', destination: '/api/webhooks/meta' }]
  },

  async headers() {
    /* Content-Security-Policy.
     *
     * The site was serving `upgrade-insecure-requests` and nothing else, which
     * is a CSP header in name only — it forces https and permits everything
     * else. The policy below adds the directives that actually stop something:
     * `object-src 'none'` (no Flash/plugin injection), `base-uri 'self'` (no
     * hijacking relative URLs by injecting a <base> tag), `form-action 'self'`
     * (no exfiltrating a submitted contact form to another origin) and
     * `frame-ancestors` (clickjacking, and it supersedes X-Frame-Options in
     * every browser that reads both).
     *
     * `script-src` keeps 'unsafe-inline'. That is a deliberate trade, not an
     * oversight: Next inlines its own bootstrap and streams RSC payloads in
     * inline scripts, and the only way to allow those strictly is a per-request
     * nonce. A nonce cannot be issued from `headers()` — it needs middleware on
     * every route, and middleware makes every route dynamic. This site is
     * statically prerendered and edge-cached on purpose (see the Cache-Control
     * note below); trading that for a stricter script-src would cost far more
     * than it buys. Revisit if the site ever goes dynamic anyway.
     *
     * Third-party origins are the analytics tags in `components/seo/analytics.tsx`
     * (GTM, GA4, Clarity, Meta Pixel) plus the keyless Google Maps embed. Each
     * is gated behind its own env var, so a deploy with none of them set simply
     * never uses these allowances. */
    /* Next's dev server compiles every chunk with webpack's `eval-source-map`
       devtool and React Refresh evaluates its updates the same way, so a dev
       bundle is hundreds of `eval()` calls. `script-src` without
       'unsafe-eval' blocks all of them: the page server-renders correctly and
       then fails to hydrate, which on /admin/login surfaces as the
       "Sign-in could not load" boundary in `admin/(auth)/error.tsx` blaming
       AUTH_SECRET, and everywhere else as a blank page. The relaxation is
       scoped to `next dev` — the production bundle contains no `eval`, so
       shipping it there would weaken the policy for nothing. */
    const isDev = process.env.NODE_ENV !== 'production'
    const devScriptSrc = isDev ? " 'unsafe-eval'" : ''
    /* HMR runs over a websocket on the same origin. CSP 3 makes `'self'`
       cover ws:/wss: for that origin, but not every browser in use has caught
       up, so dev names it outright rather than depending on it. */
    const devConnectSrc = isDev ? ' ws: wss:' : ''

    const csp = [
      "default-src 'self'",
      `script-src 'self' 'unsafe-inline'${devScriptSrc} https://www.googletagmanager.com https://www.google-analytics.com https://www.clarity.ms https://connect.facebook.net`,
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data: blob: https:",
      "font-src 'self' data:",
      `connect-src 'self'${devConnectSrc} https://www.googletagmanager.com https://www.google-analytics.com https://*.google-analytics.com https://*.clarity.ms https://connect.facebook.net`,
      "frame-src 'self' https://www.google.com https://www.googletagmanager.com",
      "worker-src 'self' blob:",
      "manifest-src 'self'",
      "object-src 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "frame-ancestors 'self'",
      'upgrade-insecure-requests',
    ].join('; ')

    const securityHeaders = [
      { key: 'Content-Security-Policy', value: csp },
      { key: 'X-Content-Type-Options', value: 'nosniff' },
      { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
      { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
      { key: 'X-DNS-Prefetch-Control', value: 'on' },
      {
        key: 'Permissions-Policy',
        value: 'camera=(), microphone=(), geolocation=(), interest-cohort=()',
      },
      {
        key: 'Strict-Transport-Security',
        value: 'max-age=63072000; includeSubDomains; preload',
      },
    ]

    const immutable = [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }]

    /* Rules are applied in order and a later one wins for the same key, so the
       blanket cache rule below comes first and the assets that really are
       immutable re-assert themselves after it. */
    return [
      { source: '/:path*', headers: securityHeaders },

      /* ------------------------------------------------------------------
         How long the CDN may hold a page

         Next stamps statically prerendered pages with
         `s-maxage=31536000, stale-while-revalidate` — cache for a year — and
         Hostinger's edge takes it literally. Every build gives its JavaScript
         new hashed filenames and deletes the old ones, so a page held at the
         edge from before a deploy asks for chunks the server no longer has.
         They 404, React cannot hydrate, and every element still holding its
         server-rendered `opacity: 0` never becomes visible: a blank page,
         served from cache, for as long as the edge keeps it.

         That is not hypothetical. The home page was pinned this way for over
         two hours while every other page was fine, purely because that copy
         happened to be cached during a deploy.

         A minute at the edge with five more of stale-while-revalidate keeps
         essentially all of the benefit — traffic still collapses onto cached
         responses — while bounding the damage to minutes rather than a year.
         ------------------------------------------------------------------ */
      {
        source: '/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=0, s-maxage=60, stale-while-revalidate=300',
          },
        ],
      },

      /* Hashed filenames: a new build cannot collide with these, so they are
         safe to keep for a year. This has to come after the blanket rule or
         every asset would be re-fetched every minute. */
      { source: '/_next/static/:path*', headers: immutable },

      /* Route handlers decide their own freshness — /api/version in particular
         must never be answered from a cache, since a cached answer would report
         the previous deploy as the current one. */
      { source: '/api/:path*', headers: [{ key: 'Cache-Control', value: 'no-store, max-age=0' }] },

      /* …except the OG image endpoint, which is expensive to generate and
         changes only when its query string does. */
      {
        source: '/api/og',
        headers: [
          {
            key: 'Cache-Control',
            value: 'public, max-age=3600, s-maxage=604800, stale-while-revalidate=604800',
          },
        ],
      },
      {
        // Immutable caching for pre-generated media.
        source: '/images/:path*',
        headers: immutable,
      },
      {
        source: '/feed.xml',
        headers: [
          { key: 'Content-Type', value: 'application/rss+xml; charset=utf-8' },
          { key: 'Cache-Control', value: 'public, max-age=3600, s-maxage=86400' },
        ],
      },
    ]
  },
}

export default nextConfig
