import { execSync } from 'node:child_process'

/*
 * Which commit this build came from.
 *
 * Deploys here are pull-based: cron on the server notices origin/main has moved
 * and builds it. Nothing reports back, so "did my push actually go live?" was
 * answerable only by looking for a change on the page and guessing — and a cron
 * that silently stopped fetching looks exactly like a deploy that has not
 * finished yet. Baking the commit into the build lets /api/version answer it,
 * and lets CI wait for a specific commit rather than a plausible-looking page.
 *
 * Read at build time from the checkout being built, which is the server's own
 * checkout during a deploy. Git being absent is not an error — it just means
 * the build cannot identify itself, and the endpoint says so.
 */
function resolveBuildSha() {
  const provided = process.env.BUILD_SHA || process.env.GITHUB_SHA
  if (provided) return provided.trim()

  try {
    return execSync('git rev-parse HEAD', {
      stdio: ['ignore', 'pipe', 'ignore'],
      encoding: 'utf8',
    }).trim()
  } catch {
    return ''
  }
}

/*
 * Canonical host. Every URL the site emits — canonical tags, sitemap entries,
 * JSON-LD @ids, RSS links — is built from NEXT_PUBLIC_SITE_URL through
 * `absoluteUrl()`, so the www/non-www redirect below derives its target from
 * that same value and cannot drift out of agreement with them.
 */
const canonicalOrigin = new URL(
  (process.env.NEXT_PUBLIC_SITE_URL || 'https://globifytech.com').replace(/\/$/, ''),
).origin
const canonicalHost = new URL(canonicalOrigin).host

/** The twin of the canonical host: www.x when x is canonical, and vice versa. */
const duplicateHost = canonicalHost.startsWith('www.')
  ? canonicalHost.slice(4)
  : `www.${canonicalHost}`

/*
 * Where the build is written.
 *
 * Normally `.next`, which is also what `next start` serves. During a deploy it
 * is pointed somewhere else so the build never touches the directory being
 * served — see scripts/deploy.sh. Building in place rewrites `.next/static`
 * while Passenger is still serving prerendered HTML that references the old
 * hashed filenames, and for the minutes that takes, every visitor gets a page
 * whose stylesheets 404: correct markup, no CSS, unreadable.
 */
const distDir = process.env.NEXT_DIST_DIR || '.next'

/** @type {import('next').NextConfig} */
const nextConfig = {
  distDir,
  reactStrictMode: true,
  poweredByHeader: false,
  compress: true,

  /* Inlined into the build, so `/api/version` reports the commit that produced
     the running bundle rather than whatever the server's checkout happens to be
     sitting on now — those differ precisely when a deploy half-failed, which is
     the case worth detecting. */
  env: {
    BUILD_SHA: resolveBuildSha(),
    BUILD_TIME: new Date().toISOString(),
  },

  // Trailing slashes off => single canonical URL shape (no duplicate-content penalty).
  trailingSlash: false,

  images: {
    // Local WebP/AVIF assets are pre-generated by scripts/generate-images.mjs.
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [360, 420, 640, 768, 1024, 1280, 1536, 1920],
    imageSizes: [64, 96, 128, 192, 256, 384],
    minimumCacheTTL: 60 * 60 * 24 * 365,
    dangerouslyAllowSVG: true,
    contentDispositionType: 'attachment',
    contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
  },

  experimental: {
    // Tree-shake barrel imports from icon/animation packages -> smaller JS payload.
    optimizePackageImports: ['lucide-react', 'framer-motion'],
  },

  // 301 redirects. Add legacy URLs here as the site evolves.
  async redirects() {
    /* The catalogue was consolidated from 14 courses to 7. These keep the
       retired URLs alive for inbound links and for the blog articles that
       still reference them. Where no close equivalent exists the redirect
       goes to the catalogue rather than to a misleading match.

       The second group is a different lineage. globifytech.com has been serving
       a build whose catalogue matches no commit in this repository, so the URLs
       currently indexed by Google are not the ones above — they are these. The
       first deploy of this repository retires all eight of them at once, and
       without a redirect each becomes a 404 on a page that already has ranking
       and inbound links. */
    const retiredCourses = [
      ['ai-and-automation', 'full-stack-development-with-ai'],
      ['web-development', 'full-stack-development-with-ai'],
      ['python-programming', 'full-stack-development-with-ai'],
      ['wordpress-development', 'full-stack-development-with-ai'],
      ['digital-marketing', 'digital-media-marketing-with-ai'],
      ['ui-ux-design', 'graphic-designing'],
      ['canva-mastery', 'graphic-designing'],
      ['amazon-virtual-assistant', 'tiktok-shop'],
      ['shopify-dropshipping', 'tiktok-shop'],

      // Live today, retired by the first deploy — near-identical renames.
      ['digital-marketing-with-ai', 'digital-media-marketing-with-ai'],
      ['full-stack-web-development-with-ai', 'full-stack-development-with-ai'],
      ['tiktok-shop-mastery', 'tiktok-shop'],
    ].map(([from, to]) => ({
      source: `/courses/${from}`,
      destination: `/courses/${to}`,
      permanent: true,
    }))

    /* No successor close enough to name. "Agentic AI" and "AI Chatbots &
       Business Automation" have no counterpart in the seven, and pointing them
       at Facebook Automation because both say "automation" would land visitors
       on a course about something else — worse than the catalogue, which at
       least lets them choose. */
    const retiredToCatalogue = [
      'freelancing-mastery',
      'office-automation',
      'agentic-ai-and-workflow-management',
      'ai-chatbots-and-business-automation',
    ].map((from) => ({
      source: `/courses/${from}`,
      destination: '/courses',
      permanent: true,
    }))

    /* Host consolidation: send the duplicate host to the canonical one so
       Google merges the signals instead of splitting them across two hosts.
       `has` matches the Host header exactly, so localhost, *.vercel.app
       previews and the canonical host itself are all left untouched — only
       the literal duplicate redirects, which rules out a loop. */
    const canonicalHostRedirect = {
      source: '/:path*',
      has: [{ type: 'host', value: duplicateHost }],
      destination: `${canonicalOrigin}/:path*`,
      permanent: true,
    }

    return [
      canonicalHostRedirect,
      ...retiredCourses,
      ...retiredToCatalogue,
      { source: '/home', destination: '/', permanent: true },
      { source: '/courses/index', destination: '/courses', permanent: true },
      { source: '/blogs', destination: '/blog', permanent: true },
      { source: '/blogs/:slug', destination: '/blog/:slug', permanent: true },
      { source: '/contact-us', destination: '/contact', permanent: true },
      { source: '/about-us', destination: '/about', permanent: true },
      { source: '/privacy', destination: '/privacy-policy', permanent: true },
      { source: '/terms-and-conditions', destination: '/terms', permanent: true },
      { source: '/rss', destination: '/feed.xml', permanent: true },
    ]
  },

  /* The callback URL registered in the Meta developer app is the short, public
     `/webhook`, while the handler lives with the other route handlers under
     `/api/webhooks/meta`. A rewrite serves both from one implementation — and
     it has to be a rewrite, not a redirect: Meta does not follow 3xx on webhook
     delivery, so the registered path must answer 200 itself. */
  async rewrites() {
    return [{ source: '/webhook', destination: '/api/webhooks/meta' }]
  },

  async headers() {
    const securityHeaders = [
      { key: 'X-Content-Type-Options', value: 'nosniff' },
      { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
      { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
      { key: 'X-DNS-Prefetch-Control', value: 'on' },
      {
        key: 'Permissions-Policy',
        value: 'camera=(), microphone=(), geolocation=(), interest-cohort=()',
      },
      {
        key: 'Strict-Transport-Security',
        value: 'max-age=63072000; includeSubDomains; preload',
      },
    ]

    return [
      { source: '/:path*', headers: securityHeaders },
      {
        // Immutable caching for pre-generated media.
        source: '/images/:path*',
        headers: [
          { key: 'Cache-Control', value: 'public, max-age=31536000, immutable' },
        ],
      },
      {
        source: '/feed.xml',
        headers: [
          { key: 'Content-Type', value: 'application/rss+xml; charset=utf-8' },
          { key: 'Cache-Control', value: 'public, max-age=3600, s-maxage=86400' },
        ],
      },
    ]
  },
}

export default nextConfig
